name: plante
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 21.05.202+13

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  get_it: ^6.0.0
  shared_preferences: ^2.0.5
  intl: ^0.17.0
  google_maps_flutter: ^2.0.1
  permission_handler: ^6.0.1
  geolocator: ^7.0.1
  http: ^0.13.0
  qr_code_scanner: ^0.4.0
  openfoodfacts:
    path: submodules/openfoodfacts-dart
  image_picker: ^0.7.2+1
  image_cropper: ^1.4.0
  flutter_svg: ^0.21.0-nullsafety.0
  google_sign_in: ^5.0.1
  firebase_core: ^1.0.4
  firebase_auth: ^1.1.1
  firebase_crashlytics: ^2.0.4
  device_info: ^2.0.0
  json_annotation: ^4.0.1
  built_value: ^8.0.4
  built_collection: ^5.0.0
  expandable: ^5.0.1
  fimber: ^0.6.1
  fimber_io: ^0.6.2
  flutter_archive: ^3.0.0
  path_provider: ^2.0.1
  share: ^2.0.1
  url_launcher: ^6.0.3
  google_fonts: ^2.0.0
  palette_generator: ^0.3.0
  photo_view: ^0.11.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.14.5
  mockito: ^5.0.3
  build_runner: ^1.12.2
  json_serializable: ^4.1.0
  built_value_generator: ^8.0.4
  flutter_launcher_icons: ^0.9.0


flutter_icons:
  android: "icon"
  ios: true
  image_path: "icon/icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  generate: true

  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Bold.ttf
          weight: 700

    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Medium.ttf
          weight: 500

    - family: OpenSans
      fonts:
        - asset: fonts/OpenSans-Regular.ttf
          weight: 400
        - asset: fonts/OpenSans-Bold.ttf
          weight: 700

  assets:
    - assets/google_icon.svg
    - assets/back_arrow.svg
    - assets/add_photo.svg
    - assets/cancel_circle.svg
    - assets/info_icon.svg
    - assets/veg_status_vegan.svg
    - assets/veg_status_vegetarian.svg
    - assets/veg_status_negative.svg
    - assets/veg_status_unknown.png
    - assets/veg_status_source_auto.svg
    - assets/veg_status_source_community.svg
    - assets/veg_status_source_moderator.svg
    - assets/veg_status_source_unknown.svg
    - assets/expand_down.svg
    - assets/expand_up.svg
    - assets/report.svg
    - assets/barcode.svg
    - assets/history.svg
    - assets/cancel.svg
    - assets/menu_ellipsis.svg
    - assets/flash_disabled.svg
    - assets/flash_enabled.svg
    - assets/settings.svg
    - assets/barcode_scan_mode.svg
    - assets/barcode_type_mode.svg
