name: untitled_vegan_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.0.1+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  get_it: ^6.0.0
  shared_preferences: ^2.0.4
  intl: ^0.17.0
  google_maps_flutter: ^2.0.1
  permission_handler: ^6.0.1
  geolocator: ^7.0.1
  http: ^0.13.0
  qr_code_scanner: ^0.4.0
  openfoodfacts: ^1.0.2-beta
  image_picker: ^0.7.2+1
  image_cropper: ^1.4.0
  flutter_svg: ^0.21.0-nullsafety.0
  google_sign_in: ^5.0.1
  firebase_core: ^0.4.0+9
  firebase_auth: ^0.14.0+5
  device_info: ^2.0.0
  json_annotation: ^4.0.1
  built_value: ^8.0.4
  either_option: ^2.0.1-dev.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.14.5
  mockito: ^5.0.3
  build_runner: ^1.12.2
  json_serializable: ^4.1.0
  built_value_generator: ^8.0.4

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  generate: true

  assets:
    - assets/google_icon.svg
