name: plante
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 21.12.201+53

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  get_it: ^7.1.3
  shared_preferences: ^2.0.6
  intl: ^0.17.0
  google_maps_flutter: ^2.0.6
  permission_handler: ^8.1.1
  geolocator: ^7.0.1
  http: ^0.13.0
  qr_code_scanner: ^0.5.1
  openfoodfacts:
    path: submodules/openfoodfacts-dart
  image_picker: ^0.8.0+1
  flutter_svg: ^0.22.0
  google_sign_in: ^5.0.1
  firebase_core: ^1.10.0
  firebase_crashlytics: ^2.2.2
  firebase_analytics: ^8.3.2
  device_info: ^2.0.0
  built_value: ^8.0.4
  built_collection: ^5.0.0
  expandable: ^5.0.1
  fimber: ^0.6.1
  fimber_io: ^0.6.2
  flutter_archive: ^4.0.1
  path_provider: ^2.0.1
  share: ^2.0.1
  url_launcher: ^6.0.10
  palette_generator: ^0.3.0
  photo_view: ^0.12.0
  google_maps_cluster_manager: ^1.0.0
  crop_your_image: ^0.6.0+1
  flutter_image_compress: ^1.0.0
  package_info_plus: ^1.0.2
  diffutil_dart: ^2.0.0+1
  visibility_detector: ^0.2.0
  sign_in_with_apple: ^3.1.0
  flutter_linkify: ^5.0.2
  sqflite: ^2.0.0+3
  sqflite_common_ffi: ^2.0.0+1
  fuzzywuzzy: ^0.1.4
  map_launcher: ^2.1.1
  flutter_config: ^2.0.0
  flutter_riverpod: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.16.8
  mockito: ^5.0.10
  build_runner: ^2.0.6
  json_serializable: ^4.1.3
  built_value_generator: ^8.1.1
  flutter_launcher_icons: ^0.9.0
  trotter: ^2.0.0-dev.1

flutter_icons:
  android: "icon"
  ios: true
  image_path: "icon/icon.png"
  image_path_ios: "icon/icon_ios.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  generate: true

  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Bold.ttf
          weight: 700

    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Medium.ttf
          weight: 500

    - family: OpenSans
      fonts:
        - asset: fonts/OpenSans-Regular.ttf
          weight: 400
        - asset: fonts/OpenSans-Bold.ttf
          weight: 700

  assets:
    - assets/google_icon.svg
    - assets/back_arrow.svg
    - assets/add_photo.svg
    - assets/cancel_circle.svg
    - assets/info_icon.svg
    - assets/veg_status_vegan.svg
    - assets/veg_status_negative.svg
    - assets/veg_status_unknown.png
    - assets/veg_status_source_auto.svg
    - assets/veg_status_source_community.svg
    - assets/veg_status_source_moderator.svg
    - assets/veg_status_source_unknown.svg
    - assets/veg_status_warning_icon.svg
    - assets/expand_down.svg
    - assets/expand_up.svg
    - assets/marker_abstract.svg
    - assets/barcode.svg
    - assets/history.svg
    - assets/cancel.svg
    - assets/menu_ellipsis.svg
    - assets/flash_disabled.svg
    - assets/flash_enabled.svg
    - assets/settings.svg
    - assets/barcode_scan_mode.svg
    - assets/barcode_type_mode.svg
    - assets/map_marker_empty.svg
    - assets/map_marker_filled.svg
    - assets/map_marker_selected.svg
    - assets/map_marker_suggestions.svg
    - assets/map_marker_group_empty.svg
    - assets/map_marker_group_filled.svg
    - assets/map_marker_accented.svg
    - assets/map_marker_group_accented.svg
    - assets/map_marker_group_selected.svg
    - assets/map_marker_group_suggestions.svg
    - assets/map_filters.svg
    - assets/my_location.svg
    - assets/plus_shop.svg
    - assets/cancel_circle_light.svg
    - assets/map_check_mark.svg
    - assets/location.svg
    - assets/list_drag_n_drop.svg
    - assets/search.svg
    - assets/empty.svg
    - assets/directions.svg
    - assets/plus_small.svg
    - assets/show_on_map_small.svg
